credentials: # Provides the usernames, names, passwords, and emails, and other user data.
  usernames:
    eric: # User name
      email: ericledat00@outook.com 
      failed_login_attempts: 0
      logged_in: False 
      name: Eric Le
      password: qwerty 
cookie:
  expiry_days: 0 # Specifies the number of days before the re-authentication cookie automatically expires on the client's browser.
  key: some_signature_key # Specifies the key that will be used to hash the signature of the re-authentication cookie.
  name: some_cookie_name # Specifies the name of the re-authentication cookie stored on the client's browser for password-less re-authentication.
pre-authorized: # Provides the list of emails of unregistered users who are authorized to register.
  emails:
  - something@gmail.com