import streamlit as st
from gui.keys.st_ss import ST_SS

def render_output_display_options(mf4_file_disabled:bool) -> None:
    """
    Renders the output display options section.

    Parameters:
    mf4_file_disabled (bool): A flag indicating whether the MF4 file is disabled.

    Returns:
    None
    """
    st_ss = st.session_state
    st.subheader("Output Display Settings ⚙️")
    
    # Output Display settings
    with st.container(border=True):
        col1, _, col3= st.columns([0.35,0.05, 0.35])
        with col1:         
            st.toggle(label="Show plan", disabled=mf4_file_disabled, 
                    help="Show the plan composed by the agent.",
                    key=ST_SS.TOGGLE_SHOW_PLAN_KEY)
    
        with col3:
            st.toggle(label="Show code", disabled=mf4_file_disabled,
                    help="Show the code generated by the agent.",
                    key=ST_SS.TOGGLE_SHOW_CODE_KEY)
        
        col1, _, col3= st.columns([0.35,0.05, 0.35])
        with col1:
            st.toggle(label="Run code", disabled=mf4_file_disabled,
                    help="Execute the generated code by the agent.",
                    key=ST_SS.TOGGLE_RUN_CODE_KEY)
        with col3:
            st.toggle(label="Show file source", disabled=mf4_file_disabled,
                    help="Show file source of the output",
                    key=ST_SS.TOGGLE_SHOW_FILE_SOURCE)
                
                # Clear chat history
        def clear_chat_history():
            """Clear the chat history stored in session state."""
            st_ss[ST_SS.CHAT_HISTORY_KEY] = []
        
        st.empty()
        st.button("Clear Conversation 🗑️", 
                help="Clear Chat",
                type="primary",
                on_click=clear_chat_history, 
                disabled=mf4_file_disabled,
                use_container_width=True)